mission smile view 리팩토링
DeveloperAcademy-POSTECH/MC2-Team8-Ssok pull request #149
Opened 2023-08-09 13:15 UTC by ChangJin-Lee

# 작업내용
- #139 
- mission smile view를 리팩토링합니다.

# 참고사항
- smile, blink 두개를 함수 하나로 합쳤어요

# 스크린샷
|<img src = "https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-Ssok/assets/54494793/b6ef45a2-dde5-4607-a2ce-35f591a42595">|
|:--:|
|하나의 함수로 합침|

# 이슈 및 해결방안
- 

# 알림
- 코드에 문제가 있거나 기능이 제대로 동작하지 않는다면 코멘트 달아주세요.
- 다른 문제도 언제든 환영합니다.

2023-08-09 13:26 UTC, pingse requested changes

2023-08-09 13:56 UTC, ChangJin-Lee commented on 개인정보처리방침.md
> +< CSSP >('https://codeisfuture.tistory.com/'이하 'CSSP')은(는) 다음의 목적을 위하여 개인정보를 처리합니다. 처리하고 있는 개인정보는 다음의 목적 이외의 용도로는 이용되지 않으며 이용 목적이 변경되는 경우에는 「개인정보 보호법」 제18조에 따라 별도의 동의를 받는 등 필요한 조치를 이행할 예정입니다.
다음에 해당하는 부분을 바꿨어요.

수정 전

```
https://codeisfuture.tistory.com/
```

수정 후

```
https://github.com/DeveloperAcademy-POSTECH/MC2-Team8-Ssok
```

언제든지 다른 의견 있으면 주세여

2023-08-12 15:30 UTC, ChangJin-Lee commented on Ssok/Views/MissionSmileView.swift
> +    private func arView(arStatus: Bool, arViewModel: ARViewModel, colorStatus: Bool, state: Bool, largePearlIndex: Int, guideMessage1: String, guideMessage2: String) -> some View{
네 선데이.
좋은 말씀 감사해요.
코드는 다음과 같이 변경했어요.

변경 전
```swift
private func arView(arStatus: Bool, arViewModel: ARViewModel, colorStatus: Bool, state: Bool, largePearlIndex: Int, guideMessage1: String, guideMessage2: String) -> some View
```

변경 후

```swift
 private func makeArView(arStatus: Bool, arViewModel: ARViewModel, colorStatus: Bool, state: Bool, largePearlIndex: Int, guideMessage1: String, guideMessage2: String) -> some View
```

다른 문의사항이나 의견이 있으면 언제든지 알려주세요.

2023-08-17 06:59 UTC, snacknam approved these changes
LGTM👍🏻

2023-08-17 06:59 UTC, snacknam commented on Ssok/Model/ARModel.swift
> +enum ArViewController{
띄어쓰기 부탁드려요🙂

2023-08-18 03:06 UTC, pingse approved these changes

2023-08-20 15:07 UTC, merged